package model.eo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 28 09:49:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileUpdDwnVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FileUpdDwnVOImpl() {
    }
}

