package model.eo;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 28 09:49:19 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileUpdDwnVORowImpl extends ViewRowImpl {
    public static final int ENTITY_FILEUPDDWN = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FileName,
        Path,
        ContentType,
        DocumentFile;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int PATH = AttributesEnum.Path.index();
    public static final int CONTENTTYPE = AttributesEnum.ContentType.index();
    public static final int DOCUMENTFILE = AttributesEnum.DocumentFile.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FileUpdDwnVORowImpl() {
    }

    /**
     * Gets FileUpdDwn entity object.
     * @return the FileUpdDwn
     */
    public EntityImpl getFileUpdDwn() {
        return (EntityImpl) getEntity(ENTITY_FILEUPDDWN);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for PATH using the alias name Path.
     * @return the PATH
     */
    public String getPath() {
        return (String) getAttributeInternal(PATH);
    }

    /**
     * Sets <code>value</code> as attribute value for PATH using the alias name Path.
     * @param value value to set the PATH
     */
    public void setPath(String value) {
        setAttributeInternal(PATH, value);
    }

    /**
     * Gets the attribute value for CONTENT_TYPE using the alias name ContentType.
     * @return the CONTENT_TYPE
     */
    public String getContentType() {
        return (String) getAttributeInternal(CONTENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTENT_TYPE using the alias name ContentType.
     * @param value value to set the CONTENT_TYPE
     */
    public void setContentType(String value) {
        setAttributeInternal(CONTENTTYPE, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_FILE using the alias name DocumentFile.
     * @return the DOCUMENT_FILE
     */
    public BlobDomain getDocumentFile() {
        return (BlobDomain) getAttributeInternal(DOCUMENTFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_FILE using the alias name DocumentFile.
     * @param value value to set the DOCUMENT_FILE
     */
    public void setDocumentFile(BlobDomain value) {
        setAttributeInternal(DOCUMENTFILE, value);
    }
}

