package model.rvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 25 01:55:03 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InfluenceLevelImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InfluenceLevelImpl() {
    }
}

