package model.rvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 09:03:06 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesStagesLookup_arImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesStagesLookup_arImpl() {
    }
}

