package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 24 13:29:37 IST 2017
// ---------------------------------------------------------------------
public interface UserApplicationModule extends ApplicationModule {
    void populateCusConJun(Integer aId, Integer cId);

    void populateAcOppJun(Integer aId, Integer oId);

    void populateNoteOppJun(Integer nId, Integer oId);
}

