package model.uvo;

import java.sql.ResultSet;

import oracle.jbo.AttributeList;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 18:57:43 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class AllManRepUVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AllManRepUVOImpl() {
    }
    @Override
    public void create() {
      super.create();
      this.setManageRowsByKey(true);
    }


}

