package model.uvo;

import oracle.jbo.AttributeList;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 18:57:42 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllManRepUVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Manid,
        Repid,
        RepRefid,
        AreAssociated,
        UserManagerUVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int MANID = AttributesEnum.Manid.index();
    public static final int REPID = AttributesEnum.Repid.index();
    public static final int REPREFID = AttributesEnum.RepRefid.index();
    public static final int AREASSOCIATED = AttributesEnum.AreAssociated.index();
    public static final int USERMANAGERUVO1 = AttributesEnum.UserManagerUVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AllManRepUVORowImpl() {
    }
    
    /**
     * Gets the attribute value for the calculated attribute Manid.
     * @return the Manid
     */
    public Long getManid() {
        return (Long) getAttributeInternal(MANID);
    }

    /**
     * Gets the attribute value for the calculated attribute Repid.
     * @return the Repid
     */
    public Long getRepid() {
        return (Long) getAttributeInternal(REPID);
    }

    /**
     * Gets the attribute value for the calculated attribute RepRefid.
     * @return the RepRefid
     */
    public String getRepRefid() {
        return (String) getAttributeInternal(REPREFID);
    }

    /**
     * Gets the attribute value for the calculated attribute AreAssociated.
     * @return the AreAssociated
     */
    public Boolean getAreAssociated() {
        return (Boolean) getAttributeInternal(AREASSOCIATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AreAssociated.
     * @param value value to set the  AreAssociated
     */
    public void setAreAssociated(Boolean value) {
        Boolean oldvalue=getAreAssociated();
        setAttributeInternal(AREASSOCIATED, value);
        if(oldvalue!= value){
            if(value){
                createIntersectionRow(getManid().intValue(),getRepid().intValue());
            }
            else {
                deleteIntersectionRow();
            }
        }
        
    }
    
    public void createIntersectionRow(Integer manId,Integer repId){
        RowSet rowSet=getUserManagerUVO1();
        Row row=rowSet.createRow();
        row.setAttribute("ManagerId",manId);
        row.setAttribute("UserId",repId);
        rowSet.insertRow(row);
        getDBTransaction().commit();
    }
    
    public void deleteIntersectionRow(){
        RowSet rowSet=getUserManagerUVO1();
        if(rowSet.getRowCount()==1){
            Row atRangeIndex=rowSet.getRowAtRangeIndex(0);
            atRangeIndex.remove();
            getDBTransaction().commit();
        }
    }
    /**
     * Gets the view accessor <code>RowSet</code> UserManagerUVO1.
     */
    public RowSet getUserManagerUVO1() {
        return (RowSet) getAttributeInternal(USERMANAGERUVO1);
    }
}

