package model.uvo;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 20 20:02:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllRoleUserPairUVO_AKRowImpl extends ViewRowImpl {
    public static final int ENTITY_ROLESEO = 0;
    public static final int ENTITY_AKUSERSEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EndDate,
        RoleDescription,
        RoleId,
        RoleName,
        StartDate,
        AddressId,
        Email,
        EndDate1,
        FirstName,
        Gender,
        LastName,
        MiddleName,
        PicId,
        StartDate1,
        UName,
        UPassword,
        UserId,
        UserRefId,
        AreAssociated,
        RoleUserUVO_AK1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ROLEDESCRIPTION = AttributesEnum.RoleDescription.index();
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ADDRESSID = AttributesEnum.AddressId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ENDDATE1 = AttributesEnum.EndDate1.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int PICID = AttributesEnum.PicId.index();
    public static final int STARTDATE1 = AttributesEnum.StartDate1.index();
    public static final int UNAME = AttributesEnum.UName.index();
    public static final int UPASSWORD = AttributesEnum.UPassword.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERREFID = AttributesEnum.UserRefId.index();
    public static final int AREASSOCIATED = AttributesEnum.AreAssociated.index();
    public static final int ROLEUSERUVO_AK1 = AttributesEnum.RoleUserUVO_AK1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AllRoleUserPairUVO_AKRowImpl() {
    }

    /**
     * Gets RolesEO entity object.
     * @return the RolesEO
     */
    public EntityImpl getRolesEO() {
        return (EntityImpl) getEntity(ENTITY_ROLESEO);
    }

    /**
     * Gets AKUsersEO entity object.
     * @return the AKUsersEO
     */
    public EntityImpl getAKUsersEO() {
        return (EntityImpl) getEntity(ENTITY_AKUSERSEO);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for ROLE_DESCRIPTION using the alias name RoleDescription.
     * @return the ROLE_DESCRIPTION
     */
    public String getRoleDescription() {
        return (String) getAttributeInternal(ROLEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_DESCRIPTION using the alias name RoleDescription.
     * @param value value to set the ROLE_DESCRIPTION
     */
    public void setRoleDescription(String value) {
        setAttributeInternal(ROLEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ROLE_ID using the alias name RoleId.
     * @return the ROLE_ID
     */
    public DBSequence getRoleId() {
        return (DBSequence) getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_ID using the alias name RoleId.
     * @param value value to set the ROLE_ID
     */
    public void setRoleId(DBSequence value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for ROLE_NAME using the alias name RoleName.
     * @return the ROLE_NAME
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_NAME using the alias name RoleName.
     * @param value value to set the ROLE_NAME
     */
    public void setRoleName(String value) {
        setAttributeInternal(ROLENAME, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for ADDRESS_ID using the alias name AddressId.
     * @return the ADDRESS_ID
     */
    public Long getAddressId() {
        return (Long) getAttributeInternal(ADDRESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_ID using the alias name AddressId.
     * @param value value to set the ADDRESS_ID
     */
    public void setAddressId(Long value) {
        setAttributeInternal(ADDRESSID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate1.
     * @return the END_DATE
     */
    public Timestamp getEndDate1() {
        return (Timestamp) getAttributeInternal(ENDDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate1.
     * @param value value to set the END_DATE
     */
    public void setEndDate1(Timestamp value) {
        setAttributeInternal(ENDDATE1, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for GENDER using the alias name Gender.
     * @return the GENDER
     */
    public Long getGender() {
        return (Long) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER using the alias name Gender.
     * @param value value to set the GENDER
     */
    public void setGender(Long value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @return the MIDDLE_NAME
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @param value value to set the MIDDLE_NAME
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for PIC_ID using the alias name PicId.
     * @return the PIC_ID
     */
    public Long getPicId() {
        return (Long) getAttributeInternal(PICID);
    }

    /**
     * Sets <code>value</code> as attribute value for PIC_ID using the alias name PicId.
     * @param value value to set the PIC_ID
     */
    public void setPicId(Long value) {
        setAttributeInternal(PICID, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate1.
     * @return the START_DATE
     */
    public Timestamp getStartDate1() {
        return (Timestamp) getAttributeInternal(STARTDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate1.
     * @param value value to set the START_DATE
     */
    public void setStartDate1(Timestamp value) {
        setAttributeInternal(STARTDATE1, value);
    }

    /**
     * Gets the attribute value for U_NAME using the alias name UName.
     * @return the U_NAME
     */
    public String getUName() {
        return (String) getAttributeInternal(UNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for U_NAME using the alias name UName.
     * @param value value to set the U_NAME
     */
    public void setUName(String value) {
        setAttributeInternal(UNAME, value);
    }

    /**
     * Gets the attribute value for U_PASSWORD using the alias name UPassword.
     * @return the U_PASSWORD
     */
    public String getUPassword() {
        return (String) getAttributeInternal(UPASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for U_PASSWORD using the alias name UPassword.
     * @param value value to set the U_PASSWORD
     */
    public void setUPassword(String value) {
        setAttributeInternal(UPASSWORD, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public DBSequence getUserId() {
        return (DBSequence) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(DBSequence value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for USER_REF_ID using the alias name UserRefId.
     * @return the USER_REF_ID
     */
    public String getUserRefId() {
        return (String) getAttributeInternal(USERREFID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_REF_ID using the alias name UserRefId.
     * @param value value to set the USER_REF_ID
     */
    public void setUserRefId(String value) {
        setAttributeInternal(USERREFID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AreAssociated.
     * @return the AreAssociated
     */
    public Boolean getAreAssociated() {
        return (Boolean) getAttributeInternal(AREASSOCIATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AreAssociated.
     * @param value value to set the  AreAssociated
     */
    public void setAreAssociated(Boolean value) {
        Boolean oldValue=getAreAssociated();
        setAttributeInternal(AREASSOCIATED, value);
        if(oldValue!=value){
            if(value){
                createIntersectionRow(Integer.parseInt(getRoleId().toString()),Integer.parseInt(getUserId().toString()));
            }
            else {
                deleteIntersectionRow();
            }
        }
    }

    /**
     * Gets the view accessor <code>RowSet</code> RoleUserUVO_AK1.
     */
    public RowSet getRoleUserUVO_AK1() {
        return (RowSet) getAttributeInternal(ROLEUSERUVO_AK1);
    }
    
    public void createIntersectionRow(Integer roleId,Integer userId){
        RowSet rowSet=getRoleUserUVO_AK1();
        Row row=rowSet.createRow();
        row.setAttribute("RoleId",roleId);
        row.setAttribute("UserId",userId);
        rowSet.insertRow(row);
        getDBTransaction().commit();
    }
    public void deleteIntersectionRow(){
        RowSet rowSet=getRoleUserUVO_AK1();
        if(rowSet.getRowCount()==1) {
            Row atRangeIndex=rowSet.getRowAtRangeIndex(0);
            atRangeIndex.remove();
            getDBTransaction().commit();
        }
    }
    
}

