package model.uvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 20:03:36 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class ManagerUVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ManagerUVOImpl() {
    }
    @Override
    public void create(){
        super.create();
        this.setManageRowsByKey(true);
    }
}

