package model.rvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 22 22:44:11 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OppertunityOfUser_arImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OppertunityOfUser_arImpl() {
    }
}

