package model.uvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 21 12:24:48 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskUVO_arVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TaskUVO_arVOImpl() {
    }


    /**
     * Returns the bind variable value for customerIdFilter.
     * @return bind variable value for customerIdFilter
     */
    public Long getcustomerIdFilter() {
        return (Long) getNamedWhereClauseParam("customerIdFilter");
    }

    /**
     * Sets <code>value</code> for bind variable customerIdFilter.
     * @param value value to bind as customerIdFilter
     */
    public void setcustomerIdFilter(Long value) {
        setNamedWhereClauseParam("customerIdFilter", value);
    }


}

